################################################
#######Behavioral sequencing data analysis######
################################################

#### Packages used ####
library(data.table)
library(Hmisc)
library(tidyverse)
library(igraph)
library(rqdatatable)
library(writexl)

#### Import data ####
# It should be a binary table generated by BORIS as a .tsv
# Group1:
setwd("C:\\Users\\bclem\\OneDrive\\Documents\\Formation\\Stage\\WAIKATO\\Data\\D.minor mating records\\BORIS project\\Heavy_Binary_Group1")
g1.G26xJ203 <- as.data.frame(fread("G26 x J203_No focal subject.tsv"))
g1.G30xJ210 <- as.data.frame(fread("G30 x J210_No focal subject.tsv"))
g1.H30xH71 <- as.data.frame(fread("H30 x H71_No focal subject.tsv"))
g1.H45xH65 <- as.data.frame(fread("H45 x H65_No focal subject.tsv"))
g1.H62xJ132 <- as.data.frame(fread("H62 x J132_No focal subject.tsv"))
g1.J101xJ204 <- as.data.frame(fread("J101 x J204_No focal subject.tsv"))
g1.J102xJ206 <- as.data.frame(fread("J102 x J206_No focal subject.tsv"))
g1.J110xH67 <- as.data.frame(fread("J110 x H67_No focal subject.tsv"))
g1.J124xG42 <- as.data.frame(fread("J124 x G42_No focal subject.tsv"))
g1.J144xG39 <- as.data.frame(fread("J144 x G39_No focal subject.tsv"))
g1.J183xH26 <- as.data.frame(fread("J183 x H26_No focal subject.tsv"))
g1.J189xJ112 <- as.data.frame(fread("J189 x J112_No focal subject.tsv"))
g1.J190xJ42 <- as.data.frame(fread("J190 x J42_No focal subject.tsv"))
g1.J191xJ68 <- as.data.frame(fread("J191 x J68_No focal subject.tsv"))
g1.J201xG43 <- as.data.frame(fread("J201 x G43_No focal subject.tsv"))
# Group2:
setwd("C:\\Users\\bclem\\OneDrive\\Documents\\Formation\\Stage\\WAIKATO\\Data\\D.minor mating records\\BORIS project\\Heavy_Binary_Group2")
g2.G30xH52 <- as.data.frame(fread("G30 x H52_No focal subject.tsv"))
g2.H30xG38 <- as.data.frame(fread("H30 x G38_No focal subject.tsv"))
g2.H62xG33 <- as.data.frame(fread("H62 x G33_No focal subject.tsv"))
g2.J101xH76 <- as.data.frame(fread("J101 x H76_No focal subject.tsv"))
g2.J102xJ161 <- as.data.frame(fread("J102 x J161_No focal subject.tsv"))
g2.J110xJ140 <- as.data.frame(fread("J110 x J140_No focal subject.tsv"))
g2.J124xG32 <- as.data.frame(fread("J124 x G32_No focal subject.tsv"))
g2.J144xG38 <- as.data.frame(fread("J144 x G38_No focal subject.tsv"))
g2.J183xG35 <- as.data.frame(fread("J183 x G35_No focal subject.tsv"))
g2.J190xJ212 <- as.data.frame(fread("J190 x J212_No focal subject.tsv"))

#### Creating functions ####

### Function for removing behaviors that are no longer used ###
cleaning.behaviours <- function(data) {
  # Remove orientation
  if ("Orientation" %in% colnames(data)) {
    data <- data[,-which(colnames(data)=="Orientation")]
  }
  # Remove Random locomotion 
  if ("Random Locomotion" %in% colnames(data)) {
    data <- data[,-which(colnames(data)=="Random Locomotion")]
  }
  # Remove Vibration interaction 
  if ("Vibration interaction" %in% colnames(data)) {
    data <- data[,-which(colnames(data)=="Vibration interaction")]
  }
  # Remove Approach (Should be removed later)
  if ("Approach" %in% colnames(data)) {
    data <- data[,-which(colnames(data)=="Approach")]
  }
  # Add "Courtship start" behavior
  data$Courtship.Start <- c(1,rep(0,nrow(data)-1))
  # Add "Mounting start" behavior
  i <- which(data$Mounted != dplyr::lag((data$Mounted)))
  data$Mounting.Start <- c(rep(0,i[1]-1),1,rep(0,nrow(data)-i[1]))
  
  return(data)
}

### Function for exclusive behaviors, treated as a string of "A + B +..." ###
### Will be used in the latter function ###
exclusive.behaviours <- function(text) {
  if (grepl("Abdomen Tapping",text,fixed=TRUE)) {
    text <- "Abdomen Tapping"
  }
  if (grepl("Mounting.Start",text,fixed=TRUE)) {
    text <- "Mounting.Start"
  }
  if (grepl("Courtship.Start",text,fixed=TRUE)) {
    text <- "Courtship.Start"
  }
  if (grepl("Freezing",text,fixed=TRUE)) {
    if (grepl("Mounted",text,fixed=TRUE)) {
      text <- "Mounted + Freezing"
    } else { text <- "Freezing" }
  }
  if (grepl("Retreat",text,fixed=TRUE)) {
    text <- "Retreat"
  }
  if (grepl("Female Kill",text,fixed=TRUE)) {
    text <- "Female Kill"
  }
  if (grepl("Pedipalp Insertion",text,fixed=TRUE)) {
    text <- "Pedipalp Insertion"
  }
  if (text == "Mounted") {
    text <- "Mounted + Freezing"
  }
  text
}

### Function to aggregate behaviors ### 
behavioural.aggregation <- function(data) {
  
  # Creating an empty data frame for the final output
  output <- data.frame(matrix(nrow = 0, ncol = 3))
  colnames(output) <- c("Behaviour", "START", "STOP")
  
  # Loop for the first row (A)
  i <- 1
  while (i < nrow(data)) {
    
    # Convert binary data to text for row A
    textA <- ""
    while (textA == "") {
      vec <- c()
      for (z in 2:ncol(data)) {
        if (data[i, z] == 1) {
          vec <- append(vec,colnames(data)[z])
        }
      }
      
      textA <- paste(vec, collapse = " + ")
      textA <- exclusive.behaviours(textA)
      if (textA == "") {
        i <- i+1
      }
    }
    
    # Retain beginning time of the behavior
    startA <- data[i,1]
    
    # Loop for the second row (B)
    j <- i + 1
    # Convert binary data to text for row B
    vec <- c()
    for (z in 2:ncol(data)) {
      if (data[j, z] == 1) {
        vec <- append(vec,colnames(data)[z])
      }
    }
    textB <- paste(vec, collapse = " + ")
    textB <- exclusive.behaviours(textB)

    # Loop to see if behavior has changed
    while ((textA == textB | textB=="") & j < nrow(data)) {
      j <- j + 1
      # Update textB
      vec <- c()
      for (z in 2:ncol(data)) {
        if (data[j, z] == 1) {
          vec <- append(vec,colnames(data)[z])
        }
      }
      textB <- paste(vec, collapse = " + ")
      textB <- exclusive.behaviours(textB)
    }
    
    # Retain the timecode of the changing behavior
    stopA <- data[j,1]
    
    # Add the row to the output dataframe
    output[nrow(output)+1,] <- c(textA,startA,stopA)
    
    i <- j
    
  }
  
  # Changing strings to numeric for the time codes
  output$START <- as.numeric(output$START)
  output$STOP <- as.numeric(output$STOP)
  # Creating rows for the duration of each behavior and the ID
  output$Duration <- output$STOP - output$START
  output$ID <- rep(deparse(substitute(data)),nrow(output))
  
  # Final result
  output
}

### Function to format behaviors for transition analysis ### 
format.behaviours <- function(data) {
  # Creating and empty data frame
  output <- as.data.frame(matrix(nrow=nrow(data)-1 ,ncol = 3))
  colnames(output) <- c("Behavior 0","Behavior 1","Mating ID")
  # Adding the behaviours :
  output[,1] <- data[-nrow(data),1]
  output[,2] <- data[-1,1]
  output[,3] <- data[-1,5]
  # Final output
  output
}

### Function to remove micro-behaviors ###
remove.microbehaviours <- function(data,s) {
  list <- c()
  exempted <- c("Courtship.Start","Mounting.Start","Abdomen Tapping")
  for (i in 1:nrow(data)) {
    if (data[i,4] <= 1 & !(data[i,1] %in% exempted)) {
      list <- c(list,i)
    }
  }
  data <- data[-list,]
  return(data)
}

### Merge consecutive behaviours ###
merge.behaviours <- function(data) {
  i <- 1
  while (i <= (nrow(data)-1)) {
    if (data[i,1] == data[(i+1),1]) {
      data[i,3] <- data[i+1,3]
      data[i,4] <- data[i,4]+data[i+1,4]
      data <- data[-(i+1),]
      i <- i-1
    }
    i <- i+1
  }
  return(data)
}

#### Formatting of my data ####

## Remove useless behaviors
# First group
g1.G26xJ203 <- cleaning.behaviours(g1.G26xJ203)
g1.G30xJ210 <- cleaning.behaviours(g1.G30xJ210)
g1.H30xH71 <- cleaning.behaviours(g1.H30xH71) ##
g1.H45xH65 <- cleaning.behaviours(g1.H45xH65)
g1.H62xJ132 <- cleaning.behaviours(g1.H62xJ132)
g1.J101xJ204 <- cleaning.behaviours(g1.J101xJ204)
g1.J102xJ206 <- cleaning.behaviours(g1.J102xJ206)
g1.J110xH67 <- cleaning.behaviours(g1.J110xH67)
g1.J124xG42 <- cleaning.behaviours(g1.J124xG42)
g1.J144xG39 <- cleaning.behaviours(g1.J144xG39)
g1.J183xH26 <- cleaning.behaviours(g1.J183xH26)
g1.J189xJ112 <- cleaning.behaviours(g1.J189xJ112)
g1.J190xJ42 <- cleaning.behaviours(g1.J190xJ42)
g1.J191xJ68 <- cleaning.behaviours(g1.J191xJ68)
g1.J201xG43 <- cleaning.behaviours(g1.J201xG43)
# Second group
g2.G30xH52 <- cleaning.behaviours(g2.G30xH52)
g2.H30xG38 <- cleaning.behaviours(g2.H30xG38) ##
g2.H62xG33 <- cleaning.behaviours(g2.H62xG33)
g2.J101xH76 <- cleaning.behaviours(g2.J101xH76)
g2.J102xJ161 <- cleaning.behaviours(g2.J102xJ161)
g2.J110xJ140 <- cleaning.behaviours(g2.J110xJ140)
g2.J124xG32 <- cleaning.behaviours(g2.J124xG32)
g2.J144xG38 <- cleaning.behaviours(g2.J144xG38)
g2.J183xG35 <- cleaning.behaviours(g2.J183xG35)
g2.J190xJ212 <- cleaning.behaviours(g2.J190xJ212)

## Aggregation
# First group
ag.g1.G26xJ203 <- behavioural.aggregation(g1.G26xJ203)
ag.g1.G30xJ210 <- behavioural.aggregation(g1.G30xJ210)
ag.g1.H30xH71 <- behavioural.aggregation(g1.H30xH71) ##
ag.g1.H45xH65 <-behavioural.aggregation(g1.H45xH65)
ag.g1.H62xJ132 <- behavioural.aggregation(g1.H62xJ132)
ag.g1.J101xJ204 <- behavioural.aggregation(g1.J101xJ204)
ag.g1.J102xJ206 <- behavioural.aggregation(g1.J102xJ206)
ag.g1.J110xH67 <- behavioural.aggregation(g1.J110xH67)
ag.g1.J124xG42 <- behavioural.aggregation(g1.J124xG42)
ag.g1.J144xG39 <- behavioural.aggregation(g1.J144xG39)
ag.g1.J183xH26 <- behavioural.aggregation(g1.J183xH26)
ag.g1.J189xJ112 <- behavioural.aggregation(g1.J189xJ112)
ag.g1.J190xJ42 <- behavioural.aggregation(g1.J190xJ42)
ag.g1.J191xJ68 <- behavioural.aggregation(g1.J191xJ68)
ag.g1.J201xG43 <- behavioural.aggregation(g1.J201xG43)
# Second group
ag.g2.G30xH52 <- behavioural.aggregation(g2.G30xH52)
ag.g2.H30xG38 <- behavioural.aggregation(g2.H30xG38) ##
ag.g2.H62xG33 <- behavioural.aggregation(g2.H62xG33)
ag.g2.J101xH76 <- behavioural.aggregation(g2.J101xH76)
ag.g2.J102xJ161 <- behavioural.aggregation(g2.J102xJ161)
ag.g2.J110xJ140 <- behavioural.aggregation(g2.J110xJ140)
ag.g2.J124xG32 <- behavioural.aggregation(g2.J124xG32)
ag.g2.J144xG38 <- behavioural.aggregation(g2.J144xG38)
ag.g2.J183xG35 <- behavioural.aggregation(g2.J183xG35)
ag.g2.J190xJ212 <- behavioural.aggregation(g2.J190xJ212)

## Remove micro behaviors
# First group
ag.g1.G26xJ203 <- remove.microbehaviours(ag.g1.G26xJ203)
ag.g1.G30xJ210 <- remove.microbehaviours(ag.g1.G30xJ210)
ag.g1.H30xH71 <- remove.microbehaviours(ag.g1.H30xH71) ##
ag.g1.H45xH65 <-remove.microbehaviours(ag.g1.H45xH65)
ag.g1.H62xJ132 <- remove.microbehaviours(ag.g1.H62xJ132)
ag.g1.J101xJ204 <- remove.microbehaviours(ag.g1.J101xJ204)
ag.g1.J102xJ206 <- remove.microbehaviours(ag.g1.J102xJ206)
ag.g1.J110xH67 <- remove.microbehaviours(ag.g1.J110xH67)
ag.g1.J124xG42 <- remove.microbehaviours(ag.g1.J124xG42)
ag.g1.J144xG39 <- remove.microbehaviours(ag.g1.J144xG39)
ag.g1.J183xH26 <- remove.microbehaviours(ag.g1.J183xH26)
ag.g1.J189xJ112 <- remove.microbehaviours(ag.g1.J189xJ112)
ag.g1.J190xJ42 <- remove.microbehaviours(ag.g1.J190xJ42)
ag.g1.J191xJ68 <- remove.microbehaviours(ag.g1.J191xJ68)
ag.g1.J201xG43 <- remove.microbehaviours(ag.g1.J201xG43)
# Second group
ag.g2.G30xH52 <- remove.microbehaviours(ag.g2.G30xH52)
ag.g2.H30xG38 <- remove.microbehaviours(ag.g2.H30xG38) ##
ag.g2.H62xG33 <- remove.microbehaviours(ag.g2.H62xG33)
ag.g2.J101xH76 <- remove.microbehaviours(ag.g2.J101xH76)
ag.g2.J102xJ161 <- remove.microbehaviours(ag.g2.J102xJ161)
ag.g2.J110xJ140 <- remove.microbehaviours(ag.g2.J110xJ140)
ag.g2.J124xG32 <- remove.microbehaviours(ag.g2.J124xG32)
ag.g2.J144xG38 <- remove.microbehaviours(ag.g2.J144xG38)
ag.g2.J183xG35 <- remove.microbehaviours(ag.g2.J183xG35)
ag.g2.J190xJ212 <- remove.microbehaviours(ag.g2.J190xJ212)

## Merge consecutive behaviours
# First group
ag.g1.G26xJ203 <- merge.behaviours(ag.g1.G26xJ203)
ag.g1.G30xJ210 <- merge.behaviours(ag.g1.G30xJ210)
ag.g1.H30xH71 <- merge.behaviours(ag.g1.H30xH71) ##
ag.g1.H45xH65 <-merge.behaviours(ag.g1.H45xH65)
ag.g1.H62xJ132 <- merge.behaviours(ag.g1.H62xJ132)
ag.g1.J101xJ204 <- merge.behaviours(ag.g1.J101xJ204)
ag.g1.J102xJ206 <- merge.behaviours(ag.g1.J102xJ206)
ag.g1.J110xH67 <- merge.behaviours(ag.g1.J110xH67)
ag.g1.J124xG42 <- merge.behaviours(ag.g1.J124xG42)
ag.g1.J144xG39 <- merge.behaviours(ag.g1.J144xG39)
ag.g1.J183xH26 <- merge.behaviours(ag.g1.J183xH26)
ag.g1.J189xJ112 <- merge.behaviours(ag.g1.J189xJ112)
ag.g1.J190xJ42 <- merge.behaviours(ag.g1.J190xJ42)
ag.g1.J191xJ68 <- merge.behaviours(ag.g1.J191xJ68)
ag.g1.J201xG43 <- merge.behaviours(ag.g1.J201xG43)
# Second group
ag.g2.G30xH52 <- merge.behaviours(ag.g2.G30xH52)
ag.g2.H30xG38 <- merge.behaviours(ag.g2.H30xG38) ##
ag.g2.H62xG33 <- merge.behaviours(ag.g2.H62xG33)
ag.g2.J101xH76 <- merge.behaviours(ag.g2.J101xH76)
ag.g2.J102xJ161 <- merge.behaviours(ag.g2.J102xJ161)
ag.g2.J110xJ140 <- merge.behaviours(ag.g2.J110xJ140)
ag.g2.J124xG32 <- merge.behaviours(ag.g2.J124xG32)
ag.g2.J144xG38 <- merge.behaviours(ag.g2.J144xG38)
ag.g2.J183xG35 <- merge.behaviours(ag.g2.J183xG35)
ag.g2.J190xJ212 <- merge.behaviours(ag.g2.J190xJ212)

## Export aggregated behaviors
# First group
setwd("C:\\Users\\bclem\\OneDrive\\Documents\\Formation\\Stage\\WAIKATO\\Data\\D.minor mating records\\BORIS project\\Aggregated_Group1")
write.csv(ag.g1.G26xJ203,file="Aggregated_G26xJ203.csv")
write.csv(ag.g1.G30xJ210,file="Aggregated_G30xJ210.csv")
write.csv(ag.g1.H30xH71,file="Aggregated_H30xH71.csv")
write.csv(ag.g1.H45xH65,file="Aggregated_H45xH65.csv")
write.csv(ag.g1.H62xJ132,file="Aggregated_H62xJ132.csv")
write.csv(ag.g1.J101xJ204,file="Aggregated_J101xJ204.csv")
write.csv(ag.g1.J102xJ206,file="Aggregated_J102xJ206.csv")
write.csv(ag.g1.J110xH67,file="Aggregated_J110xH67.csv")
write.csv(ag.g1.J124xG42,file="Aggregated_J124xG42.csv")
write.csv(ag.g1.J144xG39,file="Aggregated_J144xG39.csv")
write.csv(ag.g1.J183xH26,file="Aggregated_J183xH26.csv")
write.csv(ag.g1.J189xJ112,file="Aggregated_J189xJ112.csv")
write.csv(ag.g1.J190xJ42,file="Aggregated_J190xJ42.csv")
write.csv(ag.g1.J191xJ68,file="Aggregated_J191xJ68.csv")
write.csv(ag.g1.J201xG43,file="Aggregated_J201xG43.csv")
# Second group
setwd("C:\\Users\\bclem\\OneDrive\\Documents\\Formation\\Stage\\WAIKATO\\Data\\D.minor mating records\\BORIS project\\Aggregated_Group2")
write.csv(ag.g2.G30xH52,file="Aggregated_G30xH52.csv")
write.csv(ag.g2.H30xG38,file="Aggregated_H30xG38.csv")
write.csv(ag.g2.H62xG33,file="Aggregated_H62xG33.csv")
write.csv(ag.g2.J101xH76,file="Aggregated_J101xH76.csv")
write.csv(ag.g2.J102xJ161,file="Aggregated_J102xJ161.csv")
write.csv(ag.g2.J110xJ140,file="Aggregated_J110xJ140.csv")
write.csv(ag.g2.J124xG32,file="Aggregated_J124xG32.csv")
write.csv(ag.g2.J144xG38,file="Aggregated_J144xG38.csv")
write.csv(ag.g2.J183xG35,file="Aggregated_J183xG35.csv")
write.csv(ag.g2.J190xJ212,file="Aggregated_J190xJ212.csv")

## Behavior transitions
# First group
tr.g1.G26xJ203 <- format.behaviours(ag.g1.G26xJ203)
tr.g1.G30xJ210 <- format.behaviours(ag.g1.G30xJ210)
tr.g1.H30xH71 <- format.behaviours(ag.g1.H30xH71) ##
tr.g1.H45xH65 <-format.behaviours(ag.g1.H45xH65) 
tr.g1.H62xJ132 <- format.behaviours(ag.g1.H62xJ132)
tr.g1.J101xJ204 <- format.behaviours(ag.g1.J101xJ204)
tr.g1.J102xJ206 <- format.behaviours(ag.g1.J102xJ206)
tr.g1.J110xH67 <- format.behaviours(ag.g1.J110xH67)
tr.g1.J124xG42 <- format.behaviours(ag.g1.J124xG42)
tr.g1.J144xG39 <- format.behaviours(ag.g1.J144xG39)
tr.g1.J183xH26 <- format.behaviours(ag.g1.J183xH26)
tr.g1.J189xJ112 <- format.behaviours(ag.g1.J189xJ112)
tr.g1.J190xJ42 <- format.behaviours(ag.g1.J190xJ42)
tr.g1.J191xJ68 <- format.behaviours(ag.g1.J191xJ68)
tr.g1.J201xG43 <- format.behaviours(ag.g1.J201xG43)
# Second group
tr.g2.G30xH52 <- format.behaviours(ag.g2.G30xH52)
tr.g2.H30xG38 <- format.behaviours(ag.g2.H30xG38) ##
tr.g2.H62xG33 <- format.behaviours(ag.g2.H62xG33)
tr.g2.J101xH76 <- format.behaviours(ag.g2.J101xH76)
tr.g2.J102xJ161 <- format.behaviours(ag.g2.J102xJ161)
tr.g2.J110xJ140 <- format.behaviours(ag.g2.J110xJ140)
tr.g2.J124xG32 <- format.behaviours(ag.g2.J124xG32)
tr.g2.J144xG38 <- format.behaviours(ag.g2.J144xG38)
tr.g2.J183xG35 <- format.behaviours(ag.g2.J183xG35)
tr.g2.J190xJ212 <- format.behaviours(ag.g2.J190xJ212)

#Export Behavior transitions
# First group
setwd("C:\\Users\\bclem\\OneDrive\\Documents\\Formation\\Stage\\WAIKATO\\Data\\D.minor mating records\\BORIS project\\Transition_Group1")
write.csv(tr.g1.G26xJ203,file="Transition_G26xJ203.csv")
write.csv(tr.g1.G30xJ210,file="Transition_G30xJ210.csv")
write.csv(tr.g1.H30xH71,file="Transition_H30xH71.csv")
write.csv(tr.g1.H45xH65,file="Transition_H45xH65.csv")
write.csv(tr.g1.H62xJ132,file="Transition_H62xJ132.csv")
write.csv(tr.g1.J101xJ204,file="Transition_J101xJ204.csv")
write.csv(tr.g1.J102xJ206,file="Transition_J102xJ206.csv")
write.csv(tr.g1.J110xH67,file="Transition_J110xH67.csv")
write.csv(tr.g1.J124xG42,file="Transition_J124xG42.csv")
write.csv(tr.g1.J144xG39,file="Transition_J144xG39.csv")
write.csv(tr.g1.J183xH26,file="Transition_J183xH26.csv")
write.csv(tr.g1.J189xJ112,file="Transition_J189xJ112.csv")
write.csv(tr.g1.J190xJ42,file="Transition_J190xJ42.csv")
write.csv(tr.g1.J191xJ68,file="Transition_J191xJ68.csv")
write.csv(tr.g1.J201xG43,file="Transition_J201xG43.csv")
# Second group
setwd("C:\\Users\\bclem\\OneDrive\\Documents\\Formation\\Stage\\WAIKATO\\Data\\D.minor mating records\\BORIS project\\Transition_Group2")
write.csv(tr.g2.G30xH52,file="Transition_G30xH52.csv")
write.csv(tr.g2.H30xG38,file="Transition_H30xG38.csv")
write.csv(tr.g2.H62xG33,file="Transition_H62xG33.csv")
write.csv(tr.g2.J101xH76,file="Transition_J101xH76.csv")
write.csv(tr.g2.J102xJ161,file="Transition_J102xJ161.csv")
write.csv(tr.g2.J110xJ140,file="Transition_J110xJ140.csv")
write.csv(tr.g2.J124xG32,file="Transition_J124xG32.csv")
write.csv(tr.g2.J144xG38,file="Transition_J144xG38.csv")
write.csv(tr.g2.J183xG35,file="Transition_J183xG35.csv")
write.csv(tr.g2.J190xJ212,file="Transition_J190xJ212.csv")

## Gathering of all trials in two groups
# Group1
group1 <-
  bind_rows(
    tr.g1.G26xJ203,
    tr.g1.G30xJ210,
    tr.g1.H30xH71, ##
    tr.g1.H45xH65,
    tr.g1.H62xJ132,
    tr.g1.J101xJ204,
    tr.g1.J102xJ206,
    tr.g1.J110xH67,
    tr.g1.J124xG42,
    tr.g1.J144xG39,
    tr.g1.J183xH26,
    tr.g1.J189xJ112,
    tr.g1.J190xJ42,
    tr.g1.J191xJ68,
    tr.g1.J201xG43
  )
# Group2
group2 <-
  bind_rows(
    tr.g2.G30xH52,
    tr.g2.H30xG38, ##
    tr.g2.H62xG33,
    tr.g2.J101xH76,
    tr.g2.J102xJ161,
    tr.g2.J110xJ140,
    tr.g2.J124xG32,
    tr.g2.J144xG38,
    tr.g2.J183xG35,
    tr.g2.J190xJ212
  )

# Export Transition Group
setwd("C:\\Users\\bclem\\OneDrive\\Documents\\Formation\\Stage\\WAIKATO\\Data\\D.minor mating records\\BORIS project")
write.csv(group1,file="Transition_group1.csv")
write.csv(group2,file="Transition_group2.csv")

#### Generation of the observed adjacency matrix ####
graph1 <- graph.data.frame(group1, directed = T)
graph2 <- graph.data.frame(group2, directed = T)
adjacency.matrix1 <- get.adjacency(graph1, sparse = F)
adjacency.matrix2 <- get.adjacency(graph2, sparse = F)

# Export of Observed Adjacency matrix
write_xlsx(as.data.frame(adjacency.matrix1),"Observed_adjacency_matrix_group1.xlsx")
write_xlsx(as.data.frame(adjacency.matrix2),"Observed_adjacency_matrix_group2.xlsx")

#### Permutation test ####
# Number of permutations
m<-10000
# Empty list for the results
results1<-as.list(NA)
results2<-as.list(NA)
## Randomly shuffle the second column m times and keep each new adjacency matrix in a list
# Group1
for (i in 1:m) {
  perm <- group1
  perm[, 2] <- perm[sample(1:nrow(perm), replace = FALSE), 2]
  perm.graph <- graph.data.frame(perm, directed = T)
  perm.adjacency.matrix <- get.adjacency(perm.graph, sparse = F)
  results1[[i]] <- perm.adjacency.matrix
}
# Group2
for (i in 1:m) {
  perm <- group2
  perm[, 2] <- perm[sample(1:nrow(perm), replace = FALSE), 2]
  perm.graph <- graph.data.frame(perm, directed = T)
  perm.adjacency.matrix <- get.adjacency(perm.graph, sparse = F)
  results2[[i]] <- perm.adjacency.matrix
}

# Reorganise list: IDK what it is
listVec1 <- lapply(results1, c, recursive=TRUE)
x1 <- do.call(cbind, listVec1)
listVec2 <- lapply(results2, c, recursive=TRUE)
x2 <- do.call(cbind, listVec2)

# calculate quantiles 5 and 95%
quantiles1<-matrix(NA,nrow=nrow(x1),ncol=2)
for (i in 1:nrow(x1)){
  q<-quantile(x1[i,],probs=c(0.05,0.95))
  quantiles1[i,]<-q
}
quantiles2<-matrix(NA,nrow=nrow(x2),ncol=2)
for (i in 1:nrow(x2)){
  q<-quantile(x2[i,],probs=c(0.05,0.95))
  quantiles2[i,]<-q
}

#save matrices for each of the low and high quantile data
low1<-matrix(quantiles1[,1],nrow=14,byrow=F)
high1<-matrix(quantiles1[,2],nrow=14,byrow=F)
low2<-matrix(quantiles2[,1],nrow=14,byrow=F)
high2<-matrix(quantiles2[,2],nrow=14,byrow=F)

#rename the low and high quantile datasets to match the observed adjacency matrix
colnames(low1)<-colnames(adjacency.matrix1)
rownames(low1)<-colnames(adjacency.matrix1)
colnames(high1)<-colnames(adjacency.matrix1)
rownames(high1)<-colnames(adjacency.matrix1)
colnames(low2)<-colnames(adjacency.matrix2)
rownames(low2)<-colnames(adjacency.matrix2)
colnames(high2)<-colnames(adjacency.matrix2)
rownames(high2)<-colnames(adjacency.matrix2)

# Export high quantile matrix
write_xlsx(as.data.frame(high1),"95_quantile_adjacency_matrix_group1.xlsx")
write_xlsx(as.data.frame(high2),"95_quantile_adjacency_matrix_group2.xlsx")

#### Calculating transitional probabilities ####

#divide each cell by the row sum
trans.prob1<-round(adjacency.matrix1/rowSums(adjacency.matrix1),2) 
trans.prob1[is.nan(trans.prob1)]<-0 #replace any NaN values with 0
trans.prob1
trans.prob2<-round(adjacency.matrix2/rowSums(adjacency.matrix2),2) 
trans.prob2[is.nan(trans.prob2)]<-0 #replace any NaN values with 0
trans.prob2

# Export transitional probabilities
write_xlsx(as.data.frame(trans.prob1),"Observed_probability_matrix_group1.xlsx")
write_xlsx(as.data.frame(trans.prob2),"Observed_probability_matrix_group2.xlsx")

# Simplify to the matrix of significant behaviors
keep1<-ifelse(adjacency.matrix1>=high1,trans.prob1,0)
keep2<-ifelse(adjacency.matrix2>=high2,trans.prob2,0)

# Export simplified transitional probabilities
write_xlsx(as.data.frame(keep1),"Significant_observed_probability_matrix_group1.xlsx")
write_xlsx(as.data.frame(keep2),"Significant_observed_probability_matrix_group2.xlsx")

#### Graphical representation ####

# Creation of a network object 
network1<-graph.adjacency(keep1,weighted=TRUE,diag=TRUE)
network2<-graph.adjacency(keep2,weighted=TRUE,diag=TRUE)
# Vertex sizes
vertex_sizes1<-degree(adjacency.matrix1,rescale=TRUE)
vertex_sizes2<-degree(adjacency.matrix2,rescale=TRUE)
#set edge (arrow) weights to be equal to 5 categories of edge weight (# of transitions)
edge_weights1<-as.numeric(cut(E(network1)$weight,c(0,.1,.25,.5,.75,1),labels=c(1:5)))
edge_weights2<-as.numeric(cut(E(network2)$weight,c(0,.1,.25,.5,.75,1),labels=c(1:5)))
# Plot network
plot1<-tkplot(network1)
plot2<-tkplot(network2)
# Coordinates
coords1<-tkplot.getcoords(plot1)
coords2<-tkplot.getcoords(plot2)
# Final
plot.igraph(network1,vertex.label=V(network1)$name, vertex.label.cex = 1.25, layout=coords1,vertex.size=vertex_sizes1*150, edge.width=edge_weights1/4, edge.arrow.size=edge_weights1/4)

#### time proportion of each behavior for each individual and group ####

## Obtain time sum for each behaviour of each individual
# For first group
time.prop.g1.G26xJ203 <- ag.g1.G26xJ203 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.G30xJ210 <- ag.g1.G30xJ210 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.H30xH71 <- ag.g1.H30xH71 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.H45xH65 <- ag.g1.H45xH65 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.H62xJ132 <- ag.g1.H62xJ132 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.J101xJ204 <- ag.g1.J101xJ204 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.J102xJ206 <- ag.g1.J102xJ206 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.J110xH67 <- ag.g1.J110xH67 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.J124xG42 <- ag.g1.J124xG42 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.J144xG39 <- ag.g1.J144xG39 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.J183xH26 <- ag.g1.J183xH26 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.J189xJ112 <- ag.g1.J189xJ112 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.J190xJ42 <- ag.g1.J190xJ42 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.J191xJ68 <- ag.g1.J191xJ68 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g1.J201xG43 <- ag.g1.J201xG43 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
# For second group
time.prop.g2.G30xH52 <- ag.g2.G30xH52 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g2.H30xG38 <- ag.g2.H30xG38 %>% group_by(Behaviour) %>%summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g2.H62xG33 <- ag.g2.H62xG33 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g2.J101xH76 <- ag.g2.J101xH76 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g2.J102xJ161 <- ag.g2.J102xJ161 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g2.J110xJ140 <- ag.g2.J110xJ140 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g2.J124xG32 <- ag.g2.J124xG32 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g2.J144xG38 <- ag.g2.J144xG38 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g2.J183xG35 <- ag.g2.J183xG35 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))
time.prop.g2.J190xJ212 <- ag.g2.J190xJ212 %>% group_by(Behaviour) %>% summarise(time.prop = sum(Duration),ID = unique(ID))

## Get the time proportion by dividing by the sum
# For first group
time.prop.g1.G26xJ203$time.prop <- time.prop.g1.G26xJ203$time.prop / sum(time.prop.g1.G26xJ203$time.prop)
time.prop.g1.G30xJ210$time.prop <- time.prop.g1.G30xJ210$time.prop / sum(time.prop.g1.G30xJ210$time.prop)
time.prop.g1.H30xH71$time.prop <- time.prop.g1.H30xH71$time.prop / sum(time.prop.g1.H30xH71$time.prop)
time.prop.g1.H45xH65$time.prop <- time.prop.g1.H45xH65$time.prop / sum(time.prop.g1.H45xH65$time.prop)
time.prop.g1.H62xJ132$time.prop <- time.prop.g1.H62xJ132$time.prop / sum(time.prop.g1.H62xJ132$time.prop)
time.prop.g1.J101xJ204$time.prop <- time.prop.g1.J101xJ204$time.prop / sum(time.prop.g1.J101xJ204$time.prop)
time.prop.g1.J102xJ206$time.prop <- time.prop.g1.J102xJ206$time.prop / sum(time.prop.g1.J102xJ206$time.prop)
time.prop.g1.J110xH67$time.prop <- time.prop.g1.J110xH67$time.prop / sum(time.prop.g1.J110xH67$time.prop)
time.prop.g1.J124xG42$time.prop <- time.prop.g1.J124xG42$time.prop / sum(time.prop.g1.J124xG42$time.prop)
time.prop.g1.J144xG39$time.prop <- time.prop.g1.J144xG39$time.prop / sum(time.prop.g1.J144xG39$time.prop)
time.prop.g1.J183xH26$time.prop <- time.prop.g1.J183xH26$time.prop / sum(time.prop.g1.J183xH26$time.prop)
time.prop.g1.J189xJ112$time.prop <- time.prop.g1.J189xJ112$time.prop / sum(time.prop.g1.J189xJ112$time.prop)
time.prop.g1.J190xJ42$time.prop <- time.prop.g1.J190xJ42$time.prop / sum(time.prop.g1.J190xJ42$time.prop)
time.prop.g1.J191xJ68$time.prop <- time.prop.g1.J191xJ68$time.prop / sum(time.prop.g1.J191xJ68$time.prop)
time.prop.g1.J201xG43$time.prop <- time.prop.g1.J201xG43$time.prop / sum(time.prop.g1.J201xG43$time.prop)
# For second group
time.prop.g2.G30xH52$time.prop <- time.prop.g2.G30xH52$time.prop / sum(time.prop.g2.G30xH52$time.prop)
time.prop.g2.H30xG38$time.prop <- time.prop.g2.H30xG38$time.prop / sum(time.prop.g2.H30xG38$time.prop)
time.prop.g2.H62xG33$time.prop <- time.prop.g2.H62xG33$time.prop / sum(time.prop.g2.H62xG33$time.prop)
time.prop.g2.J101xH76$time.prop <- time.prop.g2.J101xH76$time.prop / sum(time.prop.g2.J101xH76$time.prop)
time.prop.g2.J102xJ161$time.prop <- time.prop.g2.J102xJ161$time.prop / sum(time.prop.g2.J102xJ161$time.prop)
time.prop.g2.J110xJ140$time.prop <- time.prop.g2.J110xJ140$time.prop / sum(time.prop.g2.J110xJ140$time.prop)
time.prop.g2.J124xG32$time.prop <- time.prop.g2.J124xG32$time.prop / sum(time.prop.g2.J124xG32$time.prop)
time.prop.g2.J144xG38$time.prop <- time.prop.g2.J144xG38$time.prop / sum(time.prop.g2.J144xG38$time.prop)
time.prop.g2.J183xG35$time.prop <- time.prop.g2.J183xG35$time.prop / sum(time.prop.g2.J183xG35$time.prop)
time.prop.g2.J190xJ212$time.prop <- time.prop.g2.J190xJ212$time.prop / sum(time.prop.g2.J190xJ212$time.prop)

## Group everything 
# Group1
time.prop.group1 <-
  bind_rows(
    time.prop.g1.G26xJ203,
    time.prop.g1.G30xJ210,
    time.prop.g1.H30xH71,
    time.prop.g1.H45xH65,
    time.prop.g1.H62xJ132,
    time.prop.g1.J101xJ204,
    time.prop.g1.J102xJ206,
    time.prop.g1.J110xH67,
    time.prop.g1.J124xG42,
    time.prop.g1.J144xG39,
    time.prop.g1.J183xH26,
    time.prop.g1.J189xJ112,
    time.prop.g1.J190xJ42,
    time.prop.g1.J191xJ68,
    time.prop.g1.J201xG43
  )
# Group2
time.prop.group2 <-
  bind_rows(
    time.prop.g2.G30xH52,
    time.prop.g2.H30xG38,
    time.prop.g2.H62xG33,
    time.prop.g2.J101xH76,
    time.prop.g2.J102xJ161,
    time.prop.g2.J110xJ140,
    time.prop.g2.J124xG32,
    time.prop.g2.J144xG38,
    time.prop.g2.J183xG35,
    time.prop.g2.J190xJ212
  )

## Change ID for only female ID
time.prop.group1$ID.fem <- substr(time.prop.group1$ID,4,7)
time.prop.group1 <- time.prop.group1[,-3]
colnames(time.prop.group1) <- c("Behaviour1","time.prop1","ID.fem")
time.prop.group2$ID.fem <- substr(time.prop.group2$ID,4,7)
time.prop.group2 <- time.prop.group2[,-3]
colnames(time.prop.group2) <- c("Behaviour2","time.prop2","ID.fem")

## Sort by behaviours 
LS1 <- filter(time.prop.group1, Behaviour1 == "Leg Showcase")
LS2 <- filter(time.prop.group2, Behaviour2 == "Leg Showcase")
LS.PS1 <- filter(time.prop.group1, Behaviour1 == "Leg Showcase + Pedipalp Showcase")
LS.PS2 <- filter(time.prop.group2, Behaviour2 == "Leg Showcase + Pedipalp Showcase")
Fr1 <- filter(time.prop.group1, Behaviour1 == "Freezing")
Fr2 <- filter(time.prop.group2, Behaviour2 == "Freezing")
LS.M1 <- filter(time.prop.group1, Behaviour1 == "Leg Showcase + Mounted")
LS.M2 <- filter(time.prop.group2, Behaviour2 == "Leg Showcase + Mounted")
M.F1 <- filter(time.prop.group1, Behaviour1 == "Mounted + Freezing")
M.F2 <- filter(time.prop.group2, Behaviour2 == "Mounted + Freezing")
LS.M.PS1 <- filter(time.prop.group1, Behaviour1 == "Leg Showcase + Mounted + Pedipalp Showcase")
LS.M.PS2 <- filter(time.prop.group2, Behaviour2 == "Leg Showcase + Mounted + Pedipalp Showcase")
M.PS1 <- filter(time.prop.group1, Behaviour1 == "Mounted + Pedipalp Showcase")
M.PS2 <- filter(time.prop.group2, Behaviour2 == "Mounted + Pedipalp Showcase")
PS1 <- filter(time.prop.group1, Behaviour1 == "Pedipalp Showcase")
PS2 <- filter(time.prop.group2, Behaviour2 == "Pedipalp Showcase")
R1 <- filter(time.prop.group1, Behaviour1 == "Retreat")
R2 <- filter(time.prop.group2, Behaviour2 == "Retreat")
G1 <- filter(time.prop.group1, Behaviour1 == "Grooming")
G2 <- filter(time.prop.group2, Behaviour2 == "Grooming")
G.LS1 <- filter(time.prop.group1, Behaviour1 == "Grooming + Leg Showcase")
G.LS2 <- filter(time.prop.group2, Behaviour2 == "Grooming + Leg Showcase")

# Create the empty DF:
empty.df1 <- as.data.frame(matrix(NA,nrow=15,ncol=3))
colnames(empty.df1) <- colnames(LS1)
empty.df1$ID.fem <- LS1$ID.fem
empty.df2 <- as.data.frame(matrix(NA,nrow=15,ncol=3))
colnames(empty.df2) <- colnames(LS2)
empty.df2$ID.fem <- LS1$ID.fem
# Merge1
LS1 <- natural_join(LS1,empty.df1,by="ID.fem",jointype="FULL")
LS.PS1 <- natural_join(LS.PS1,empty.df1,by="ID.fem",jointype="FULL")
Fr1 <- natural_join(Fr1,empty.df1,by="ID.fem",jointype="FULL")
LS.M1 <- natural_join(LS.M1,empty.df1,by="ID.fem",jointype="FULL")
M.F1 <- natural_join(M.F1,empty.df1,by="ID.fem",jointype="FULL")
LS.M.PS1 <- natural_join(LS.M.PS1,empty.df1,by="ID.fem",jointype="FULL")
M.PS1 <- natural_join(LS1,empty.df1,by="ID.fem",jointype="FULL")
PS1 <- natural_join(PS1,empty.df1,by="ID.fem",jointype="FULL")
R1 <- natural_join(R1,empty.df1,by="ID.fem",jointype="FULL")
G1 <- natural_join(G1,empty.df1,by="ID.fem",jointype="FULL")
G.LS1 <- natural_join(G.LS1,empty.df1,by="ID.fem",jointype="FULL")
# Merge2
LS2 <- natural_join(LS2,empty.df2,by="ID.fem",jointype="FULL")
LS.PS2 <- natural_join(LS.PS2,empty.df2,by="ID.fem",jointype="FULL")
Fr2 <- natural_join(Fr2,empty.df2,by="ID.fem",jointype="FULL")
LS.M2 <- natural_join(LS.M2,empty.df2,by="ID.fem",jointype="FULL")
M.F2 <- natural_join(M.F2,empty.df2,by="ID.fem",jointype="FULL")
LS.M.PS2 <- natural_join(LS.M.PS2,empty.df2,by="ID.fem",jointype="FULL")
M.PS2 <- natural_join(LS2,empty.df2,by="ID.fem",jointype="FULL")
PS2 <- natural_join(PS2,empty.df2,by="ID.fem",jointype="FULL")
R2 <- natural_join(R2,empty.df2,by="ID.fem",jointype="FULL")
G2 <- natural_join(G2,empty.df2,by="ID.fem",jointype="FULL")
G.LS2 <- natural_join(G.LS2,empty.df2,by="ID.fem",jointype="FULL")

## Merge df
LS <- left_join(LS1[,-2],LS2[,-2])
LS.PS <- left_join(LS.PS1[,-2],LS.PS2[,-2])
Fr <- left_join(Fr1[,-2],Fr2[,-2])
LS.M <- left_join(LS.M1[,-2],LS.M2[,-2])
M.F <- left_join(M.F1[,-2],M.F2[,-2])
LS.M.PS <- left_join(LS.M.PS1[,-2],LS.M.PS2[,-2])
M.PS <- left_join(M.PS1[,-2],M.PS2[,-2])
PS <- left_join(PS1[,-2],PS2[,-2])
R <- left_join(R1[,-2],R2[,-2])
G <- left_join(G1[,-2],G2[,-2],keep=TRUE)
G.LS <- left_join(G.LS1[,-2],G.LS2[,-2])

# Remove NAs
LS <- replace(LS,is.na(LS),0)
LS.PS <- replace(LS.PS,is.na(LS.PS),0)
Fr <- replace(Fr,is.na(Fr),0)
LS.M <- replace(LS.M,is.na(LS.M),0)
M.F <- replace(M.F,is.na(M.F),0)
LS.M.PS <- replace(LS.M.PS,is.na(LS.M.PS),0)
M.PS <- replace(M.PS,is.na(M.PS),0)
PS <- replace(PS,is.na(PS),0)
R <- replace(R,is.na(R),0)
G <- replace(G,is.na(G),0)
G.LS <- replace(G.LS,is.na(G.LS),0)
# Put NAs again for the 5 non described behaviours of group 2
LS$time.prop2[c(1,4,12,14,15)] <- NA
LS.PS$time.prop2[c(1,4,12,14,15)] <- NA
Fr$time.prop2[c(1,4,12,14,15)] <- NA
LS.M$time.prop2[c(1,4,12,14,15)] <- NA
M.F$time.prop2[c(1,4,12,14,15)] <- NA
LS.M.PS$time.prop2[c(1,4,12,14,15)] <- NA
M.PS$time.prop2[c(1,4,12,14,15)] <- NA
PS$time.prop2[c(1,4,12,14,15)] <- NA
R$time.prop2[c(1,4,12,14,15)] <- NA
G$time.prop2[c(1,4,12,14,15)] <- NA
G.LS$time.prop2[c(1,4,12,14,15)] <- NA



# Function for the jackknife:
jackknife <- function(dataset) {
  # Calculate variance of variable X
  varX <- 0
  for (i in 1:nrow(dataset)) {
    varX <- varX + (dataset[i, 3] - mean(dataset[, 3])) ^ 2
  }
  # Calculate variance of variable Y
  varY <- 0
  for (i in 1:nrow(dataset)) {
    varY <- varY + (dataset[i, 2] - mean(dataset[, 2])) ^ 2
  }
  # Calculate y, ratio of variances
  y <- varY / varX
  # Calculate all y-i
  dataset$yi <- NA
  for (i in 1:nrow(dataset)) {
    varXi <- 0
    varYi <- 0
    dataseti <- dataset[-i, ]
    for (j in 1:(nrow(dataset) - 1)) {
      varXi <- varXi + (dataseti[j, 3] - mean(dataseti[, 3])) ^ 2
      varYi <- varYi + (dataseti[j, 2] - mean(dataseti[, 2])) ^ 2
    }
    dataset[i, 4] <- varYi / varXi
  }
  # Logarithmic transformation of all y-i
  dataset$Li <- nrow(dataset) * log(y) - (nrow(dataset) - 1) * log(dataset$yi)
  # Calculate mean of the distribution (mean of all y-i)
  meanL <- mean(dataset$Li)
  # Calculate variance of distribution (variance of all y-1)
  vLi <- 0
  for (i in 1:nrow(dataset)) {
    vLi <- vLi + (dataset[i, 5] - mean(dataset[, 5])) ^ 2
  }
  VarLi <- vLi / (nrow(dataset) * (nrow(dataset) - 1))
  # Calculate Q the statistical value
  Q <- meanL / sqrt(VarLi)
  return(Q)
}

## Mean comparisons
# Wilcoxon paired test:
wilcox.test(LS$time.prop1,LS$time.prop2,paired=TRUE)
wilcox.test(LS.PS$time.prop1,LS.PS$time.prop2,paired=TRUE)
wilcox.test(Fr$time.prop1,Fr$time.prop2,paired=TRUE)
wilcox.test(LS.M$time.prop1,LS.M$time.prop2,paired=TRUE)
wilcox.test(M.F$time.prop1,M.F$time.prop2,paired=TRUE)
wilcox.test(LS.M.PS$time.prop1,LS.M.PS$time.prop2,paired=TRUE)
wilcox.test(M.PS$time.prop1,M.PS$time.prop2,paired=TRUE)
wilcox.test(PS$time.prop1,PS$time.prop2,paired=TRUE)
wilcox.test(R$time.prop1,R$time.prop2,paired=TRUE)
wilcox.test(G$time.prop1,G$time.prop2,paired=TRUE)
wilcox.test(G.LS$time.prop1,G.LS$time.prop2,paired=TRUE)

## Getting the overall time proportion :
# Merge aggregated behaviours 
# First group
ag.time.prop.group1 <- bind_rows(
ag.g1.G26xJ203,
ag.g1.G30xJ210,
ag.g1.H30xH71,
ag.g1.H45xH65,
ag.g1.H62xJ132,
ag.g1.J101xJ204,
ag.g1.J102xJ206,
ag.g1.J110xH67,
ag.g1.J124xG42,
ag.g1.J144xG39,
ag.g1.J183xH26,
ag.g1.J189xJ112,
ag.g1.J190xJ42,
ag.g1.J191xJ68,
ag.g1.J201xG43
)
# Second group
ag.time.prop.group2 <- bind_rows(
ag.g2.G30xH52,
ag.g2.H30xG38,
ag.g2.H62xG33,
ag.g2.J101xH76,
ag.g2.J102xJ161,
ag.g2.J110xJ140,
ag.g2.J124xG32,
ag.g2.J144xG38,
ag.g2.J183xG35,
ag.g2.J190xJ212
)

options(scipen = 999)
ag.time.prop.group1$Duration <- ag.time.prop.group1$Duration / sum(ag.time.prop.group1$Duration)
sum(ag.time.prop.group1$Duration)
ag.time.prop.group2$Duration <- ag.time.prop.group2$Duration / sum(ag.time.prop.group2$Duration)
sum(ag.time.prop.group2$Duration)
mean.time.group1 <- ag.time.prop.group1 %>%  group_by(Behaviour) %>% summarise(sum = sum(Duration))
mean.time.group2 <- ag.time.prop.group2 %>%  group_by(Behaviour) %>% summarise(sum = sum(Duration))
mean.time.group1$sum <- mean.time.group1$sum  * 100
mean.time.group2$sum <- mean.time.group2$sum  * 100
mean.time.group1 <- mean.time.group1[-c(1,2,12),]
mean.time.group2 <- mean.time.group2[-c(1,2,12),]
mean.time.group1$sum <- mean.time.group1$sum / sum(mean.time.group1$sum) * 100
mean.time.group2$sum <- mean.time.group2$sum / sum(mean.time.group2$sum) * 100
sum(mean.time.group1$sum)
sort(mean.time.group1$sum)
sort(mean.time.group2$sum)

## jacknife test
jacknife.function <- function(data) {
  no.na <- na.omit(data)
  dataset <- as.data.frame(matrix(nrow=nrow(no.na),ncol=3))
  colnames(dataset) <- c("Female","Virgin","Mated")
  dataset[,1] <- no.na$ID.fem
  dataset[,2] <- no.na$time.prop1
  dataset[,3] <- no.na$time.prop2
  jackknife(dataset)
}

# N.B, pour que significatif, il faut inférieur à -1.64
jacknife.function(LS) 
jacknife.function(LS.PS)
jacknife.function(Fr)
jacknife.function(LS.M)
jacknife.function(M.F)
jacknife.function(LS.M.PS)
jacknife.function(M.PS)
jacknife.function(PS)
jacknife.function(R)
jacknife.function(G)
jacknife.function(G.LS)

## Obtain Adjacency matrix for every individual:
# First group
am.g1.G26xJ203 <- get.adjacency(graph.data.frame(tr.g1.G26xJ203, directed=T), sparse = F)
am.g1.G30xJ210 <- get.adjacency(graph.data.frame(tr.g1.G30xJ210, directed=T), sparse = F)
am.g1.H30xH71 <- get.adjacency(graph.data.frame(tr.g1.H30xH71, directed=T), sparse = F)
am.g1.H45xH65 <- get.adjacency(graph.data.frame(tr.g1.H45xH65, directed=T), sparse = F)
am.g1.H62xJ132 <- get.adjacency(graph.data.frame(tr.g1.H62xJ132, directed=T), sparse = F)
am.g1.J101xJ204 <- get.adjacency(graph.data.frame(tr.g1.J101xJ204, directed=T), sparse = F)
am.g1.J102xJ206 <- get.adjacency(graph.data.frame(tr.g1.J102xJ206, directed=T), sparse = F)
am.g1.J110xH67 <- get.adjacency(graph.data.frame(tr.g1.J110xH67, directed=T), sparse = F)
am.g1.J124xG42 <- get.adjacency(graph.data.frame(tr.g1.J124xG42, directed=T), sparse = F)
am.g1.J144xG39 <- get.adjacency(graph.data.frame(tr.g1.J144xG39, directed=T), sparse = F)
am.g1.J183xH26 <- get.adjacency(graph.data.frame(tr.g1.J183xH26, directed=T), sparse = F)
am.g1.J189xJ112 <- get.adjacency(graph.data.frame(tr.g1.J189xJ112, directed=T), sparse = F)
am.g1.J190xJ42 <- get.adjacency(graph.data.frame(tr.g1.J190xJ42, directed=T), sparse = F)
am.g1.J191xJ68 <- get.adjacency(graph.data.frame(tr.g1.J191xJ68, directed=T), sparse = F)
am.g1.J201xG43 <- get.adjacency(graph.data.frame(tr.g1.J201xG43, directed=T), sparse = F)
# Second group
am.g2.G30xH52 <- get.adjacency(graph.data.frame(tr.g2.G30xH52, directed=T),sparse=F)
am.g2.H30xG38 <- get.adjacency(graph.data.frame(tr.g2.H30xG38, directed=T),sparse=F)
am.g2.H62xG33 <- get.adjacency(graph.data.frame(tr.g2.H62xG33, directed=T),sparse=F)
am.g2.J101xH76 <- get.adjacency(graph.data.frame(tr.g2.J101xH76, directed=T),sparse=F)
am.g2.J102xJ161 <- get.adjacency(graph.data.frame(tr.g2.J102xJ161, directed=T),sparse=F)
am.g2.J110xJ140 <- get.adjacency(graph.data.frame(tr.g2.J110xJ140, directed=T),sparse=F)
am.g2.J124xG32 <- get.adjacency(graph.data.frame(tr.g2.J124xG32, directed=T),sparse=F)
am.g2.J144xG38 <- get.adjacency(graph.data.frame(tr.g2.J144xG38, directed=T),sparse=F)
am.g2.J183xG35 <- get.adjacency(graph.data.frame(tr.g2.J183xG35, directed=T),sparse=F)
am.g2.J190xJ212 <- get.adjacency(graph.data.frame(tr.g2.J190xJ212, directed=T),sparse=F)

## Create an empty adjacency matrix :
full.adjacency <- matrix(NA, nrow = 14, ncol= 14)
colnames(full.adjacency) <- colnames(adjacency.matrix1)
rownames(full.adjacency) <- rownames(adjacency.matrix1)

## Create merging function 
merging <- function(matrix) {
  output <- full.adjacency
  for (i in 1:nrow(matrix)){
    for (j in 1:ncol(matrix)) {
      row <- rownames(matrix)[i]
      col <- colnames(matrix)[j]
      output[row,col] <- matrix[i,j]
    }
  }
  output[is.na(output)] <- 0
  return(output)
}

## Applying function for all individuals :
am.g1.G26xJ203 <- merging(am.g1.G26xJ203)
am.g1.G30xJ210 <- merging(am.g1.G30xJ210)
am.g1.H30xH71 <- merging(am.g1.H30xH71)
am.g1.H45xH65 <- merging(am.g1.H45xH65)
am.g1.H62xJ132 <- merging(am.g1.H62xJ132)
am.g1.J101xJ204 <- merging(am.g1.J101xJ204)
am.g1.J102xJ206 <- merging(am.g1.J102xJ206)
am.g1.J110xH67 <- merging(am.g1.J110xH67)
am.g1.J124xG42 <- merging(am.g1.J124xG42)
am.g1.J144xG39 <- merging(am.g1.J144xG39)
am.g1.J183xH26 <- merging(am.g1.J183xH26)
am.g1.J189xJ112 <- merging(am.g1.J189xJ112)
am.g1.J190xJ42 <- merging(am.g1.J190xJ42)
am.g1.J191xJ68 <- merging(am.g1.J191xJ68)
am.g1.J201xG43 <- merging(am.g1.J201xG43)
# Second group
am.g2.G30xH52 <- merging(am.g2.G30xH52)
am.g2.H30xG38 <- merging(am.g2.H30xG38)
am.g2.H62xG33 <- merging(am.g2.H62xG33)
am.g2.J101xH76 <- merging(am.g2.J101xH76)
am.g2.J102xJ161 <- merging(am.g2.J102xJ161)
am.g2.J110xJ140 <- merging(am.g2.J110xJ140)
am.g2.J124xG32 <- merging(am.g2.J124xG32)
am.g2.J144xG38 <- merging(am.g2.J144xG38)
am.g2.J183xG35 <- merging(am.g2.J183xG35)
am.g2.J190xJ212 <- merging(am.g2.J190xJ212)


## Group them in a list of adjacency matrix
# First group
am.group1 <-
  list(
    am.g1.G26xJ203,
    am.g1.G30xJ210,
    am.g1.H30xH71,
    am.g1.H45xH65,
    am.g1.H62xJ132,
    am.g1.J101xJ204,
    am.g1.J102xJ206,
    am.g1.J110xH67,
    am.g1.J124xG42,
    am.g1.J144xG39,
    am.g1.J183xH26,
    am.g1.J189xJ112,
    am.g1.J190xJ42,
    am.g1.J191xJ68,
    am.g1.J201xG43
  )
# Second group
am.group2 <-
  list(
    matrix(NA,nrow=14,ncol=14),
    am.g2.G30xH52,
    am.g2.H30xG38,
    matrix(NA,nrow=14,ncol=14),
    am.g2.H62xG33,
    am.g2.J101xH76,
    am.g2.J102xJ161,
    am.g2.J110xJ140,
    am.g2.J124xG32,
    am.g2.J144xG38,
    matrix(NA,nrow=14,ncol=14),
    am.g2.J183xG35,
    am.g2.J190xJ212,
    matrix(NA,nrow=14,ncol=14),
    matrix(NA,nrow=14,ncol=14)
  )

# Mean comparison test
pvalue.df <- as.data.frame(matrix(NA,nrow=116,ncol=3))
k <- 1
for (i in 1:14) {
  for (j in 1:14) {
    list1 <- rep(NA,15)
    list2 <- rep(NA,15)
    for (z in 1:15) {
      list1[z] <- as.numeric(am.group1[[z]][i,j])
      list2[z] <- as.numeric(am.group2[[z]][i,j])
    }
    pvalue.df[k,1] <- i
    pvalue.df[k,2] <- j
    k <- k+1
    pvalue.df[k-1,3] <- wilcox.test(list1,list2,paired=TRUE)$p.value
    print(list1)
    print("\n")
    print(list2)
    print("\n")
  }
}
view(pvalue.df)



## Calcule moyenne Groupe 1 Grooming vers Leg Display
moyList <- rep(NA,15)
for (i in 1:15) {
  moyList[i] <- as.numeric(am.group1[[i]][13,2])
}


for (z in 1:15) {
  list1[z] <- as.numeric(am.group1[[z]][i,j])
  list2[z] <- as.numeric(am.group2[[z]][i,j])
}

list1
list2

wilcox.test(list1,list2,paired=T)
